import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
  Tailwind,
  Row,
  Column,
  Button,
} from '@react-email/components';
import * as React from 'react';

export const NewsletterEmail = ({
  featuredVehicle = {
    make: 'Toyota',
    model: 'Fortuner 2.8GD-6',
    year: '2023',
    price: 'R 749,900',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
  },
  newArrivals = [
    { id: 1, name: 'VW Polo GTI', price: 'R 429,000', image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=400' },
    { id: 2, name: 'BMW 320i M-Sport', price: 'R 585,000', image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=400' },
  ],
}) => {
  return (
    <Html>
      <Tailwind
        config={{
          theme: {
            extend: {
              colors: {
                primary: '#d32f2f',
                secondary: '#1a237e',
                slate: '#0f1723',
              },
            },
          },
        }}
      >
        <Head />
        <Preview>Check out this month's premium arrivals at Everest Motoring</Preview>
        <Body className="bg-slate-50 font-sans">
          <Container className="mx-auto py-5 pb-12 w-[600px]">
            {/* Header / Logo */}
            <Section className="bg-slate py-8 text-center rounded-t-lg border-b-4 border-primary">
              <Img
                src={`${process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://everestmotoring.vercel.app'}/images/logo.png`}
                width="180"
                height="auto"
                alt="Everest Motoring"
                className="mx-auto"
              />
            </Section>

            {/* Hero Section */}
            <Section className="bg-white p-8">
              <Heading className="text-2xl font-bold text-slate m-0 mb-4">
                Showroom Highlight
              </Heading>
              <Img
                src={featuredVehicle.image}
                width="536"
                height="300"
                alt={featuredVehicle.model}
                className="rounded-lg shadow-md mb-6 object-cover"
              />
              <Heading as="h2" className="text-xl font-bold text-slate m-0">
                {featuredVehicle.year} {featuredVehicle.make} {featuredVehicle.model}
              </Heading>
              <Text className="text-primary text-2xl font-bold my-2">
                {featuredVehicle.price}
              </Text>
              <Text className="text-slate-600 leading-relaxed">
                This pristine {featuredVehicle.model} just entered our showroom. Experience the walkaround video generated by our AI engine.
              </Text>
              <Button
                className="bg-primary text-white font-bold py-3 px-6 rounded-md shadow-sm"
                href="https://everestmotoring.co.za/inventory"
              >
                View Full Specifications
              </Button>
            </Section>

            {/* Quick Links / Grid */}
            <Section className="bg-slate-100 p-8 border-t border-slate-200">
              <Heading as="h3" className="text-lg font-bold text-slate mb-4 uppercase tracking-wider">
                New Arrivals
              </Heading>
              <Row>
                {newArrivals.map((car) => (
                  <Column key={car.id} className="pr-4 py-2">
                    <Section className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm">
                      {car.image && (
                        <Img src={car.image} width="220" height="120" alt={car.name} className="rounded mb-3 object-cover" />
                      )}
                      <Text className="font-bold text-slate m-0">{car.name}</Text>
                      <Text className="text-primary font-bold m-0">{car.price}</Text>
                      <Link href="#" className="text-secondary text-sm font-bold mt-2 inline-block">
                        View Details →
                      </Link>
                    </Section>
                  </Column>
                ))}
              </Row>
            </Section>

            {/* Footer */}
            <Section className="bg-slate py-8 px-8 text-center rounded-b-lg">
              <Text className="text-slate-400 text-sm m-0">
                Everest Motoring | White River, Mpumalanga
              </Text>
              <Text className="text-slate-500 text-xs mt-4">
                You are receiving this because you subscribed to our communications.
                <br />
                <Link href="#" className="text-primary-light underline">Unsubscribe</Link>
              </Text>
            </Section>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
};

export default NewsletterEmail;
