"use client";
import { useState } from "react";

// A report is generated by cron on the 1st; this is the same job on demand, so a
// report can be produced or re-drafted for any month without waiting for the cron.
export default function GenerateReportButton({ clientId }: { clientId: string }) {
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setBusy(true);
    setError(null);
    setMessage(null);

    try {
      const res = await fetch("/api/admin/spine/reports", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ client_id: clientId }),
      });
      const body = await res.json();

      if (!res.ok) {
        setError(body.error ?? "could not generate the report");
      } else if (body.skipped) {
        setMessage(`Skipped — ${body.skipped}`);
      } else {
        setMessage(`Draft for ${body.period} is in the queue (${body.suggestions} suggestion(s)).`);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "could not generate the report");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={generate}
        disabled={busy}
        className="border border-[#2a2a3d] px-3 py-1.5 rounded-lg text-sm disabled:opacity-50"
      >
        {busy ? "Generating…" : "Generate report"}
      </button>
      {message ? <span className="text-xs text-[#6b6b8a]">{message}</span> : null}
      {error ? <span className="text-xs text-red-400">{error}</span> : null}
    </div>
  );
}
