import { NextResponse } from "next/server";
import { renderReportPdf } from "@/lib/reports/build";
import { Resend } from "resend";

export const runtime = "nodejs";
export const maxDuration = 300;

function isAuthorized(request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return process.env.NODE_ENV !== "production";
  return (request.headers.get("authorization") || "") === "Bearer " + secret;
}

/**
 * GET /api/cron/monthly-report
 *
 * Cron endpoint (1st of the month @ 07:00 UTC = 09:00 SAST).
 * Renders the PDF for the month just ended and emails it.
 */
export async function GET(request) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const recipient = process.env.REPORT_RECIPIENT_EMAIL;
  if (!recipient) {
    return NextResponse.json(
      { success: false, error: "REPORT_RECIPIENT_EMAIL not set" },
      { status: 500 }
    );
  }

  try {
    const { buffer, monthLabel, filename } = await renderReportPdf();

    // Send email with PDF attachment
    const key = process.env.RESEND_API_KEY;
    if (!key) {
      return NextResponse.json(
        { success: false, error: "RESEND_API_KEY not configured" },
        { status: 500 }
      );
    }

    const resend = new Resend(key);
    const from = process.env.RESEND_FROM_EMAIL || "Everest Motoring <onboarding@resend.dev>";

    const { error } = await resend.emails.send({
      from,
      to: recipient,
      subject: `Everest Motoring — ${monthLabel} Report`,
      text: `The ${monthLabel} performance report is attached.\n\nThis report was auto-generated by the Everest Motoring monthly reporting system.\nPowered by Ember Automation.`,
      attachments: [
        {
          filename,
          content: buffer,
        },
      ],
    });

    if (error) {
      console.error("[cron/monthly-report] email send failed:", error);
      return NextResponse.json(
        { success: false, error: error.message || "Email send failed" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, monthLabel, filename });
  } catch (err) {
    console.error("[cron/monthly-report] failed:", err);
    return NextResponse.json(
      { success: false, error: err.message },
      { status: 500 }
    );
  }
}
