import { Document, Page, Text, View, Image, StyleSheet, Font } from '@react-pdf/renderer'

const styles = StyleSheet.create({
    page: {
        backgroundColor: '#0a0a0f',
        padding: 40,
        fontFamily: 'Helvetica',
        color: '#e2e2f0',
    },
    coverPage: {
        backgroundColor: '#0a0a0f',
        padding: 60,
        justifyContent: 'center',
        alignItems: 'center',
        fontFamily: 'Helvetica',
        color: '#e2e2f0',
    },
    coverLogo: {
        width: 80,
        height: 80,
        objectFit: 'contain',
        marginBottom: 24,
    },
    coverTitle: {
        fontSize: 28,
        fontFamily: 'Helvetica-Bold',
        color: '#ffffff',
        marginBottom: 8,
    },
    coverSubtitle: {
        fontSize: 14,
        color: '#5a5a7a',
        marginBottom: 16,
    },
    coverDateRange: {
        fontSize: 12,
        color: '#8a8aaa',
        marginBottom: 32,
    },
    coverRationale: {
        fontSize: 10,
        color: '#b0b0c0',
        lineHeight: 1.5,
        textAlign: 'center',
        marginBottom: 24,
        paddingHorizontal: 40,
    },
    pillRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
        justifyContent: 'center',
        marginTop: 8,
    },
    footer: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        textAlign: 'center',
        fontSize: 8,
        color: '#3a3a5a',
    },
    postHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 8,
        borderBottom: '1px solid #1a1a27',
    },
    postNumber: {
        fontSize: 10,
        fontFamily: 'Helvetica-Bold',
        color: '#5a5a7a',
        textTransform: 'uppercase',
    },
    postDate: {
        fontSize: 10,
        color: '#5a5a7a',
    },
    taglineBlock: {
        marginBottom: 12,
    },
    // The generated images are 2:3 portrait (1024x1536). Use a 240x360pt
    // window so nothing gets cropped or stretched. Centred horizontally.
    imageWrap: {
        marginBottom: 12,
        alignItems: 'center',
    },
    image: {
        width: 240,
        height: 360,
        borderRadius: 8,
    },
    sectionLabel: {
        fontSize: 9,
        fontFamily: 'Helvetica-Bold',
        color: '#3a3a5a',
        textTransform: 'uppercase',
        marginBottom: 4,
        marginTop: 12,
    },
    bodyText: {
        fontSize: 10,
        color: '#c0c0d0',
        lineHeight: 1.4,
    },
    hashtagRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        marginTop: 4,
    },
    psychNoteLabel: {
        fontSize: 8,
        fontFamily: 'Helvetica-Bold',
        color: '#3a3a5a',
        textTransform: 'uppercase',
        marginTop: 12,
        marginBottom: 2,
    },
    psychNote: {
        fontSize: 8,
        color: '#5a5a7a',
        fontStyle: 'italic',
        marginBottom: 4,
    },
    rationale: {
        fontSize: 8,
        color: '#5a5a7a',
        fontStyle: 'italic',
        marginTop: 8,
    },
})

export function SchedulePdf({ batch, posts, brandKit, workspaceName }: {
    batch: any
    posts: any[]
    brandKit: any
    workspaceName: string
}) {
    const accent = brandKit?.primary_color || '#FFE600'
    const dateFmt = (iso: string) => {
        const d = new Date(iso)
        return d.toLocaleDateString('en-ZA', { day: 'numeric', month: 'short', year: 'numeric' })
    }
    const timeFmt = (iso: string) => {
        const d = new Date(iso)
        return d.toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit' })
    }
    const today = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'short', year: 'numeric' })

    const dates = posts.map(p => new Date(p.scheduled_at)).filter(d => !isNaN(d.getTime()))
    const dateRange = dates.length > 0
        ? `${dateFmt(dates[0].toISOString())} - ${dateFmt(dates[dates.length - 1].toISOString())}`
        : ''

    return (
        <Document>
            {/* Cover page */}
            <Page size="A4" style={styles.coverPage}>
                {brandKit?.logo_url && <Image src={brandKit.logo_url} style={styles.coverLogo} />}
                <Text style={styles.coverTitle}>{workspaceName}</Text>
                <Text style={styles.coverSubtitle}>30-day social media plan</Text>
                <Text style={styles.coverDateRange}>{dateRange}</Text>
                {batch.strategy_rationale && (
                    <Text style={styles.coverRationale}>{batch.strategy_rationale}</Text>
                )}
                {batch.pillars?.length > 0 && (
                    <View style={styles.pillRow}>
                        {batch.pillars.map((p: string, i: number) => (
                            <PillChip key={i} label={p} color={accent} />
                        ))}
                    </View>
                )}
                <Text style={styles.footer}>Generated by Ember Social - {today}</Text>
            </Page>

            {/* Per-post pages */}
            {posts.map((post: any, i: number) => {
                const variants = post.variants || {}
                const fbV = variants.facebook || {}
                const igV = variants.instagram || {}
                const tkV = variants.tiktok || {}
                const mediaUrl = post.media_urls?.[0] || null

                return (
                    <Page key={post.id} size="A4" style={styles.page}>
                        <View style={styles.postHeader}>
                            <Text style={styles.postNumber}>Post {i + 1}</Text>
                            <Text style={styles.postDate}>
                                {dateFmt(post.scheduled_at)} {timeFmt(post.scheduled_at)}
                            </Text>
                        </View>

                        {/* Tagline */}
                        {post.tagline && (
                            <View style={styles.taglineBlock}>
                                {post.tagline.split(' | ').map((line: string, li: number) => {
                                    const words = line.split(' ')
                                    return (
                                        <Text key={li} style={{ fontSize: 18, fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 2 }}>
                                            {words.map((word: string, wi: number) => {
                                                const clean = word.replace(/[^a-zA-Z0-9-]/g, '')
                                                const isAccent = post.tagline_accent && clean.toLowerCase() === post.tagline_accent.toLowerCase()
                                                return (
                                                    <Text key={wi} style={{ color: isAccent ? accent : '#ffffff' }}>
                                                        {wi > 0 ? ' ' : ''}{word}
                                                    </Text>
                                                )
                                            })}
                                        </Text>
                                    )
                                })}
                            </View>
                        )}

                        {/* Image — preserves 2:3 aspect, centred */}
                        {mediaUrl && (
                            <View style={styles.imageWrap}>
                                <Image src={mediaUrl} style={styles.image} />
                            </View>
                        )}

                        {/* Facebook variant */}
                        {fbV.content && (
                            <>
                                <Text style={styles.sectionLabel}>Facebook</Text>
                                <Text style={styles.bodyText}>{fbV.content}</Text>
                                {fbV.hashtags?.length > 0 && (
                                    <View style={styles.hashtagRow}>
                                        {fbV.hashtags.map((h: string, hi: number) => (
                                            <Text key={hi} style={{ fontSize: 9, color: accent }}>{h}</Text>
                                        ))}
                                    </View>
                                )}
                            </>
                        )}

                        {/* Instagram variant */}
                        {igV.content && (
                            <>
                                <Text style={styles.sectionLabel}>Instagram</Text>
                                <Text style={styles.bodyText}>{igV.content}</Text>
                                {igV.hashtags?.length > 0 && (
                                    <View style={styles.hashtagRow}>
                                        {igV.hashtags.map((h: string, hi: number) => (
                                            <Text key={hi} style={{ fontSize: 9, color: accent }}>{h}</Text>
                                        ))}
                                    </View>
                                )}
                            </>
                        )}

                        {/* TikTok variant */}
                        {tkV.content && (
                            <>
                                <Text style={styles.sectionLabel}>TikTok</Text>
                                <Text style={styles.bodyText}>{tkV.content}</Text>
                                {tkV.hashtags?.length > 0 && (
                                    <View style={styles.hashtagRow}>
                                        {tkV.hashtags.map((h: string, hi: number) => (
                                            <Text key={hi} style={{ fontSize: 9, color: accent }}>{h}</Text>
                                        ))}
                                    </View>
                                )}
                            </>
                        )}

                        {/* Psychology note */}
                        {post.psychology_note && (
                            <>
                                <Text style={styles.psychNoteLabel}>Why this works</Text>
                                <Text style={styles.psychNote}>{post.psychology_note}</Text>
                            </>
                        )}

                        {/* Rationale */}
                        {post.rationale && (
                            <Text style={styles.rationale}>{post.rationale}</Text>
                        )}

                        <Text style={styles.footer}>Generated by Ember Social - {today}</Text>
                    </Page>
                )
            })}
        </Document>
    )
}

function PillChip({ label, color }: { label: string; color: string }) {
    return (
        <View style={{
            paddingHorizontal: 8,
            paddingVertical: 3,
            borderRadius: 12,
            border: `1px solid ${color}30`,
            backgroundColor: `${color}15`,
        }}>
            <Text style={{ fontSize: 8, fontFamily: 'Helvetica-Bold', color, textTransform: 'uppercase' }}>{label}</Text>
        </View>
    )
}
