/* eslint-disable */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const heicConvert = require('heic-convert');

// Define dirs
const inputDir = path.join(__dirname, '..', 'public', 'Newpics');
const outputDir = path.join(__dirname, '..', 'public', 'images', 'gallery');
const manifestPath = path.join(__dirname, '..', 'lib', 'gallery-images.ts');

// Ensure output dir
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

async function processImages() {
    console.log('Starting image processing...');
    console.log(`Input: ${inputDir}`);
    console.log(`Output: ${outputDir}`);

    if (!fs.existsSync(inputDir)) {
        console.error('Input directory does not exist!');
        process.exit(1);
    }

    const files = fs.readdirSync(inputDir);

    // Sort reverse chronological (assuming filename follows date format YYYYMMDD...)
    files.sort((a, b) => {
        return b.localeCompare(a);
    });

    const validExts = ['.jpg', '.jpeg', '.png', '.heic', '.webp'];
    const candidates = files.filter(f => validExts.includes(path.extname(f).toLowerCase()));

    console.log(`Found ${candidates.length} candidate images.`);

    // Limit to top 60 to avoid excessive build times/storage use for now, 
    // but user said "all". Let's process valid ones.
    // However, if we have 400, it might take a while.
    // Let's do all but log progress.

    const galleryImages = [];
    let successCount = 0;
    let failureCount = 0;

    for (let i = 0; i < candidates.length; i++) {
        const file = candidates[i];
        const ext = path.extname(file).toLowerCase();
        const basename = path.basename(file, ext);
        const inputPath = path.join(inputDir, file);
        const outputFilename = `${basename}.jpg`; // Convert all to jpg
        const outputPath = path.join(outputDir, outputFilename);
        const publicPath = `/images/gallery/${outputFilename}`;

        // Skip if already exists (idempotent)
        if (fs.existsSync(outputPath)) {
            // console.log(`Skipping ${file} (already exists)`);
            galleryImages.push(publicPath);
            successCount++;
            continue;
        }

        try {
            // console.log(`Processing ${i + 1}/${candidates.length}: ${file}`);

            let inputBuffer = fs.readFileSync(inputPath);

            // Convert HEIC if needed
            if (ext === '.heic') {
                inputBuffer = await heicConvert({
                    buffer: inputBuffer,
                    format: 'JPEG',
                    quality: 1
                });
            }

            await sharp(inputBuffer)
                .rotate() // Auto-rotate based on EXIF
                .resize({
                    width: 1200,
                    height: 1200,
                    fit: 'inside',
                    withoutEnlargement: true
                })
                .jpeg({ quality: 80, mozjpeg: true })
                .toFile(outputPath);

            galleryImages.push(publicPath);
            successCount++;

            if (successCount % 10 === 0) {
                console.log(`Processed ${successCount}/${candidates.length} images...`);
            }
        } catch (err) {
            console.error(`Error processing ${file}:`, err.message);
            failureCount++;
        }
    }

    console.log(`\nProcessing complete.`);
    console.log(`Success: ${successCount}`);
    console.log(`Failed: ${failureCount}`);

    // Write manifest
    const content = `// This file is auto-generated by scripts/process-images.js
export const galleryImages = ${JSON.stringify(galleryImages, null, 4)};
`;
    fs.writeFileSync(manifestPath, content);
    console.log(`Manifest written to ${manifestPath}`);
}

processImages();
